create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  stripe_event_id text not null unique,
  stripe_customer_id text,
  stripe_subscription_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  processed_at timestamptz not null default now()
);

create index if not exists billing_events_processed_at_idx
  on public.billing_events (processed_at desc);

create index if not exists billing_events_customer_idx
  on public.billing_events (stripe_customer_id)
  where stripe_customer_id is not null;

alter table public.billing_events enable row level security;

-- Billing events contain private Stripe metadata and are only read through
-- server-side service-role clients used by the owner health dashboard.
revoke all on public.billing_events from anon, authenticated;

